In [18]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense


In [2]:
text="Python is a Interpreter based Programming Language. Python is a Dynamic and High Level Language. General-Purpose programming language known for its reader" 

In [3]:
chars=sorted(list(set(text)))
char_to_index={char: i for i, char in enumerate(chars)}
index_to_char={i: char for i, char in enumerate(chars)}


In [7]:
seq_length=3
sequences=[]
labels=[]

for i in range(len(text)-seq_length):
    seq=text[i:i + seq_length]
    label=text[i + seq_length]
    sequences.append([char_to_index[char] for char in seq])
    labels.append(char_to_index[label])

x=np.array(sequences)
y=np.array(labels)
y
    

array([16, 22, 21,  0, 17, 25,  0,  9,  0,  6, 21, 26, 13, 24, 23, 24, 13,
       26, 13, 24,  0, 10,  9, 25, 13, 12,  0,  8, 24, 22, 15, 24,  9, 20,
       20, 17, 21, 15,  0,  7,  9, 21, 15, 27,  9, 15, 13,  2,  0,  8, 30,
       26, 16, 22, 21,  0, 17, 25,  0,  9,  0,  3, 30, 21,  9, 20, 17, 11,
        0,  9, 21, 12,  0,  5, 17, 15, 16,  0,  7, 13, 28, 13, 19,  0,  7,
        9, 21, 15, 27,  9, 15, 13,  2,  0,  4, 13, 21, 13, 24,  9, 19,  1,
        8, 27, 24, 23, 22, 25, 13,  0, 23, 24, 22, 15, 24,  9, 20, 20, 17,
       21, 15,  0, 19,  9, 21, 15, 27,  9, 15, 13,  0, 18, 21, 22, 29, 21,
        0, 14, 22, 24,  0, 17, 26, 25,  0, 24, 13,  9, 12, 13, 24])

In [10]:
x_one_hot=tf.one_hot(x,len(chars))
y_one_hot=tf.one_hot(y, len(chars))

x_one_hot

<tf.Tensor: shape=(151, 3, 31), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>

In [11]:
model=Sequential()

In [14]:
model.add(SimpleRNN(50, input_shape=(seq_length, len(chars)), activation='relu'))
model.add(Dense(len(chars), activation='softmax'))


In [15]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_one_hot, y_one_hot, epochs=200)


Epoch 1/200


5/5 [==============================] - 4s 10ms/step - loss: 3.4526 - accuracy: 0.0331
Epoch 2/200
5/5 [==============================] - 0s 9ms/step - loss: 3.4065 - accuracy: 0.0728
Epoch 3/200
5/5 [==============================] - 0s 9ms/step - loss: 3.3685 - accuracy: 0.0861
Epoch 4/200
5/5 [==============================] - 0s 8ms/step - loss: 3.3323 - accuracy: 0.1325
Epoch 5/200
5/5 [==============================] - 0s 8ms/step - loss: 3.2945 - accuracy: 0.1788
Epoch 6/200
5/5 [==============================] - 0s 8ms/step - loss: 3.2568 - accuracy: 0.1854
Epoch 7/200
5/5 [==============================] - 0s 7ms/step - loss: 3.2118 - accuracy: 0.1921
Epoch 8/200
5/5 [==============================] - 0s 7ms/step - loss: 3.1630 - accuracy: 0.2119
Epoch 9/200
5/5 [==============================] - 0s 7ms/step - loss: 3.1052 - accuracy: 0.2185
Epoch 10/200
5/5 [==============================] - 0s 7ms/step - loss: 3.0379 - accuracy: 0.2119
Epoch 11/200
5/5 [=======

In [17]:
start_seq="Python is Interpreter based Programming"
generated_text=start_seq

for i in range(300):
    x=np.array([[ char_to_index[char] for char in generated_text[-seq_length:]]])
    x_one_hot=tf.one_hot(x, len(chars))
    prediction=model.predict(x_one_hot)
    next_index=np.argmax(prediction)
    next_char=index_to_char[next_index]
    generated_text += next_char


print("Generated Text:")
print(generated_text)

1/1 [==============================] - 0s 26ms/step
Generated Text:
Python is Interpreter based Programming Language. General-Purpose programming Language. General-Purpose programming Language. General-Purpose programming Language. General-Purpose programming Language. General-Purpose programming Language. General-Purpose programming Language. General-Purpose programming Language. General-Purpose program
